[package]
name = "conf_macros"
description = "Derive utils for config."

version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
anyhow.workspace = true
itertools.workspace = true
proc-macro2.workspace = true
quote.workspace = true
serde.workspace = true
syn.workspace = true
trybuild.workspace = true
